apiVersion: v1
kind: Service
metadata:
  name: shf-frontendsvc
  namespace: shf-ns
spec:
  type: NodePort
  selector:
    app: shf-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30785

---
apiVersion: v1
kind: Service
metadata:
  name: shf-backendsvc
  namespace: shf-ns
spec:
  type: ClusterIP
  selector:
    app: shf-backend
  ports:
    - port: 5000
      targetPort: 5000
